version: '3.1'
services:
  n8n:
    build:
      context: .
    ports:
      - "5678:5678"
    volumes:
      - .:/home/project
      - ~/.n8n:/home/node/.n8n
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scraping_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
